version: '2.3'

services:
  main:
    container_name: hidf-engine-food_main
    build:
      context: ./
      dockerfile: Dockerfile
    runtime: nvidia
    restart: always
    links:
      - mysql
      - rabbitmq
    depends_on:
      - mysql
      - rabbitmq
    env_file:
      - "docker-compose-env/main.env"
      - "docker-compose-env/mysql.env"
      - "docker-compose-env/rabbitmq.env"
    expose:
      - "8000"
      - "22"
    volumes:
      - ./media:/workspace/media
    ports:
      - "10000:8000"
      - "10022:22"
    stdin_open: true
    tty: true

  mysql:
    container_name: hidf-engine-food_mysql
    image: mysql:latest
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file:
      - "docker-compose-env/mysql.env"
    expose:
      - "3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
  rabbitmq:
    container_name: hidf-engine-food_rabbitmq
    image: rabbitmq:3.8.14
    restart: always
    env_file:
      - "docker-compose-env/rabbitmq.env"
    expose:
      - "5672"
      - "15672"
